### ISSUE TITLE
Sunscorch can't be used repeatedly

### ISSUE THREAD

**Issue by ChitownWillie** [BartyMae/SR_Revised#20]
1st sunscorch works - but repeat attempts have no effect:

![image](https://user-images.githubusercontent.com/65503897/133773837-e3efbec3-611e-42dd-be00-66cacf8986a8.png)

**Comment by BartyMae** [comment]
Thanks, fixed it. If you want the corrected file for your current game, please send me your sppr116.spl on the G3 forums and I'll manually fix it. The issue is simply that a protection effect was set to permanent instead of temporary for undead (so actually, against non-undead, it should work repeatedly right now...but of course, it's most effective against undead).
